/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_haringat_hwip_clp_Argument */

#ifndef _Included_com_github_haringat_hwip_clp_Argument
#define _Included_com_github_haringat_hwip_clp_Argument
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
