/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_haringat_hwip_clp_Parser */

#ifndef _Included_com_github_haringat_hwip_clp_Parser
#define _Included_com_github_haringat_hwip_clp_Parser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_haringat_hwip_clp_Parser
 * Method:    parseCLI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_haringat_hwip_clp_Parser_parseCLI
  (JNIEnv *, jclass);

/*
 * Class:     com_github_haringat_hwip_clp_Parser
 * Method:    addArg
 * Signature: ([Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_haringat_hwip_clp_Parser_addArg___3Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jobjectArray, jstring);

/*
 * Class:     com_github_haringat_hwip_clp_Parser
 * Method:    addArg
 * Signature: ([Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_github_haringat_hwip_clp_Parser_addArg___3Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jclass, jobjectArray, jstring, jint);

/*
 * Class:     com_github_haringat_hwip_clp_Parser
 * Method:    addArg
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_haringat_hwip_clp_Parser_addArg__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_github_haringat_hwip_clp_Parser
 * Method:    addArg
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_github_haringat_hwip_clp_Parser_addArg__Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jclass, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
